logFilters:
  - code: YN0000  # Suppress general warnings
    level: discard
  - code: YN0060  # Suppress unmet peer dependency warnings
    level: discard
  - code: YN0061  # Suppress deprecated package warnings
    level: discard
  - code: YN0018  # Suppress all warnings
    level: discard